In [1]:
from data_fetching import MyCorr

mycorr = MyCorr("https://localhost:8443/data-service/client",'')

In [2]:
table_id = 'tab-'       
engine = 'polars'

In [3]:
help(mycorr.get_table)

Help on method get_table in module data_fetching:

get_table(
    table_id: str,
    version: Union[int, str, NoneType] = None,
    engine: str = 'pandas'
) -> Union[pandas.core.frame.DataFrame, polars.dataframe.frame.DataFrame] method of data_fetching.MyCorr instance
    Fetch table data synchronously and convert to DataFrame

    Args:
        table_id: Unique identifier for the table
        version: Version number (int) or version alias (str, e.g., 'latest', 'stable')
        engine: Data processing engine ('pandas' or 'polars')

    Returns:
        DataFrame in the specified format (pandas or polars)

    Raises:
        TypeError: If version has wrong type
        ValueError: If engine is not supported
        TableAPIError: For API-related errors
        TableConversionError: If conversion to DataFrame fails

In [4]:
version = 0
df_by_version =  mycorr.get_table(table_id,version=version , engine=engine)
display(df_by_version)

shape: (10, 10)
┌──────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬────────────┐
│ Year ┆ Industry_ag ┆ Industry_c ┆ Industry_n ┆ … ┆ Variable_n ┆ Variable_c ┆ Value  ┆ Industry_c │
│ ---  ┆ gregation_N ┆ ode_NZSIOC ┆ ame_NZSIOC ┆   ┆ ame        ┆ ategory    ┆ ---    ┆ ode_ANZSIC │
│ u32  ┆ ZSIOC       ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ u32    ┆ 06         │
│      ┆ ---         ┆ u32        ┆ str        ┆   ┆ str        ┆ str        ┆        ┆ ---        │
│      ┆ str         ┆            ┆            ┆   ┆            ┆            ┆        ┆ str        │
╞══════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total      ┆ Financial  ┆ 930995 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ income     ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Sales,     ┆ Financial  ┆ 821630 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ government ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ funding,   ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ gra…       ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest,  ┆ Financial  ┆ 84354  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ dividends  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ and        ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ donati…    ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Non-operat ┆ Financial  ┆ 25010  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ ing income ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total expe ┆ Financial  ┆ 832964 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ nditure    ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest   ┆ Financial  ┆ 55267  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ donations  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Indirect   ┆ Financial  ┆ 7426   ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ taxes      ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Depreciati ┆ Financial  ┆ 30814  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ on         ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Salaries   ┆ Financial  ┆ 147663 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and wages  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ paid       ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Redundancy ┆ Financial  ┆ 269    ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ severance  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
└──────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴────────────┘

In [5]:
version_alias='lts'
df_by_version_alias =  mycorr.get_table(table_id,version=version_alias, engine=engine)
display(df_by_version_alias)

shape: (10, 10)
┌──────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬────────────┐
│ Year ┆ Industry_ag ┆ Industry_c ┆ Industry_n ┆ … ┆ Variable_n ┆ Variable_c ┆ Value  ┆ Industry_c │
│ ---  ┆ gregation_N ┆ ode_NZSIOC ┆ ame_NZSIOC ┆   ┆ ame        ┆ ategory    ┆ ---    ┆ ode_ANZSIC │
│ u32  ┆ ZSIOC       ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ u32    ┆ 06         │
│      ┆ ---         ┆ u32        ┆ str        ┆   ┆ str        ┆ str        ┆        ┆ ---        │
│      ┆ str         ┆            ┆            ┆   ┆            ┆            ┆        ┆ str        │
╞══════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total      ┆ Financial  ┆ 930995 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ income     ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Sales,     ┆ Financial  ┆ 821630 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ government ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ funding,   ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ gra…       ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest,  ┆ Financial  ┆ 84354  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ dividends  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ and        ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ donati…    ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Non-operat ┆ Financial  ┆ 25010  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ ing income ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total expe ┆ Financial  ┆ 832964 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ nditure    ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest   ┆ Financial  ┆ 55267  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ donations  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Indirect   ┆ Financial  ┆ 7426   ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ taxes      ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Depreciati ┆ Financial  ┆ 30814  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ on         ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Salaries   ┆ Financial  ┆ 147663 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and wages  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ paid       ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Redundancy ┆ Financial  ┆ 269    ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ severance  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
└──────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴────────────┘

In [6]:
#get latest version
latest_df =  mycorr.get_table(table_id,engine=engine)
display(latest_df)

shape: (10, 10)
┌──────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬────────────┐
│ Year ┆ Industry_ag ┆ Industry_c ┆ Industry_n ┆ … ┆ Variable_n ┆ Variable_c ┆ Value  ┆ Industry_c │
│ ---  ┆ gregation_N ┆ ode_NZSIOC ┆ ame_NZSIOC ┆   ┆ ame        ┆ ategory    ┆ ---    ┆ ode_ANZSIC │
│ u32  ┆ ZSIOC       ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ u32    ┆ 06         │
│      ┆ ---         ┆ u32        ┆ str        ┆   ┆ str        ┆ str        ┆        ┆ ---        │
│      ┆ str         ┆            ┆            ┆   ┆            ┆            ┆        ┆ str        │
╞══════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total      ┆ Financial  ┆ 930995 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ income     ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Sales,     ┆ Financial  ┆ 821630 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ government ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ funding,   ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ gra…       ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest,  ┆ Financial  ┆ 84354  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ dividends  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ and        ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆ donati…    ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Non-operat ┆ Financial  ┆ 25010  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ ing income ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Total expe ┆ Financial  ┆ 832964 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ nditure    ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Interest   ┆ Financial  ┆ 55267  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ donations  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Indirect   ┆ Financial  ┆ 7426   ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ taxes      ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Depreciati ┆ Financial  ┆ 30814  ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ on         ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆            ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Salaries   ┆ Financial  ┆ 147663 ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and wages  ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ paid       ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
│ 2023 ┆ Level 1     ┆ 99999      ┆ All        ┆ … ┆ Redundancy ┆ Financial  ┆ 269    ┆ ANZSIC06   │
│      ┆             ┆            ┆ industries ┆   ┆ and        ┆ performanc ┆        ┆ divisions  │
│      ┆             ┆            ┆            ┆   ┆ severance  ┆ e          ┆        ┆ A-S        │
│      ┆             ┆            ┆            ┆   ┆            ┆            ┆        ┆ (exclud…   │
└──────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴────────────┘

In [7]:
table_info=mycorr.get_table_info(table_id)
print(table_info)

{'table_id': 'tab-0199b9e2-aa92-7ca0-a235-366b5f5c8a5c', 'schema': 'Year: uint32\nIndustry_aggregation_NZSIOC: string\nIndustry_code_NZSIOC: uint32\nIndustry_name_NZSIOC: string\nUnits: string\nVariable_code: string\nVariable_name: string\nVariable_category: string\nValue: uint32\nIndustry_code_ANZSIC06: string', 'num_columns': 10, 'num_rows': 10, 'column_names': ['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06'], 'column_types': ['uint32', 'string', 'uint32', 'string', 'string', 'string', 'string', 'string', 'uint32', 'string']}